# WhatATheme
markdown: kramdown

# URL of the Site
url: ""
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site

title: Aleksandr Andreew | Developer | It-Volunteer | Pharmacist by training
# Description of the Site |
description: ...Make yours come true
# URL of Image of the Site
siteimage: background.png
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/background.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: aleksandrandrph@gmail.com
facebook_username: thedevslot
twitter_username: thedevslot
linkedin_username: thedevslot
github_username: thedevslot

# Name of the Author
author-name: Aleksandr Andreew
# URL for the Image of the Author
author-image: assets/images/Aleksandr.jpg
# 60 Words About the Author
author-about: "Full-stack developer with a foundational background in pharmacy. I combine medical-grade precision with modern web technologies to build reliable, scalable applications. My focus is on creating tools that solve real-world problems for businesses and social organizations."
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/AleksandrAndreew-Dev

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  - scope:
      type: "posts"
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  - scope:
      type: "pages"
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
